// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SetBoxWebUI.Repository;

namespace SetBoxWebUI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191104171849_AddLastAcessDevice")]
    partial class AddLastAcessDevice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AddressId");

                    b.Property<string>("City")
                        .HasColumnName("City")
                        .HasMaxLength(255);

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("State")
                        .HasColumnName("State")
                        .HasMaxLength(2);

                    b.Property<string>("Street")
                        .HasColumnName("Street")
                        .HasMaxLength(1000);

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SetBoxAddress");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Document")
                        .HasColumnName("Document")
                        .HasMaxLength(255);

                    b.Property<string>("Fatansy")
                        .HasColumnName("Fatansy")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(500);

                    b.HasKey("CompanyId");

                    b.ToTable("SetBoxCompany");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Config", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ConfigId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("DeviceId");

                    b.Property<bool>("EnablePhoto")
                        .HasColumnName("EnablePhoto");

                    b.Property<bool>("EnableTransaction")
                        .HasColumnName("EnableTransaction");

                    b.Property<bool>("EnableVideo")
                        .HasColumnName("EnableVideo");

                    b.Property<bool>("EnableWebImage")
                        .HasColumnName("EnableWebImage");

                    b.Property<bool>("EnableWebVideo")
                        .HasColumnName("EnableWebVideo");

                    b.Property<int>("TransactionTime");

                    b.HasKey("ConfigId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("SetBoxConfigs");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContactId");

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Document")
                        .HasColumnName("Document")
                        .HasMaxLength(100);

                    b.Property<string>("Email1")
                        .HasColumnName("Email1")
                        .HasMaxLength(500);

                    b.Property<string>("Email2")
                        .HasColumnName("Email2")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(255);

                    b.Property<string>("Telephone1")
                        .HasColumnName("Telephone1")
                        .HasMaxLength(50);

                    b.Property<string>("Telephone2")
                        .HasColumnName("Telephone2")
                        .HasMaxLength(50);

                    b.HasKey("ContactId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SetBoxContact");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeviceId");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Active")
                        .HasDefaultValue(false);

                    b.Property<string>("ApkVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ApkVersion")
                        .HasMaxLength(255)
                        .HasDefaultValue("1");

                    b.Property<Guid?>("CompanyId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasColumnName("DeviceIdentifier")
                        .HasMaxLength(255);

                    b.Property<string>("DeviceName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeviceName")
                        .HasMaxLength(255)
                        .HasDefaultValue("SetBox");

                    b.Property<DateTime?>("LastAccessDateTime");

                    b.Property<string>("License")
                        .HasColumnName("License")
                        .HasMaxLength(255);

                    b.Property<string>("Manufacturer")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Manufacturer")
                        .HasMaxLength(255)
                        .HasDefaultValue("unknown");

                    b.Property<string>("Model")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Model")
                        .HasMaxLength(255)
                        .HasDefaultValue("unknown");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Name")
                        .HasMaxLength(500)
                        .HasDefaultValue("");

                    b.Property<string>("Platform")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Platform")
                        .HasMaxLength(255)
                        .HasDefaultValue("unknown");

                    b.Property<Guid?>("SupportId");

                    b.Property<string>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Version")
                        .HasMaxLength(255)
                        .HasDefaultValue("unknown");

                    b.HasKey("DeviceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SupportId");

                    b.ToTable("SetBoxDevices");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.DeviceLogAccesses", b =>
                {
                    b.Property<Guid>("DeviceLogAccessesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeviceLogAccessesId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("DeviceId");

                    b.Property<string>("IpAcessed")
                        .HasColumnName("IpAcessed");

                    b.Property<string>("Message")
                        .HasColumnName("Message")
                        .HasMaxLength(2000);

                    b.HasKey("DeviceLogAccessesId");

                    b.HasIndex("DeviceId");

                    b.ToTable("SetBoxDeviceLogAccesses");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.DeviceLogError", b =>
                {
                    b.Property<Guid>("DeviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeviceLogId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("DeviceId");

                    b.Property<string>("IpAcessed")
                        .HasColumnName("IpAcessed");

                    b.Property<string>("Level")
                        .HasColumnName("Level")
                        .HasMaxLength(20);

                    b.Property<string>("Message")
                        .HasColumnName("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceLogId");

                    b.HasIndex("DeviceId");

                    b.ToTable("SetBoxDeviceLog");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.FileCheckSum", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FileId");

                    b.Property<string>("CheckSum");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Description")
                        .HasMaxLength(500)
                        .HasDefaultValue("");

                    b.Property<string>("Extension")
                        .HasColumnName("Extension")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(255);

                    b.Property<string>("Path")
                        .HasColumnName("Path")
                        .HasMaxLength(500);

                    b.Property<long>("Size")
                        .HasColumnName("Size");

                    b.Property<string>("Url")
                        .HasColumnName("Url")
                        .HasMaxLength(4000);

                    b.HasKey("FileId");

                    b.ToTable("SetBoxFiles");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.FilesDevices", b =>
                {
                    b.Property<Guid>("DeviceId");

                    b.Property<Guid>("FileId");

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("Order");

                    b.HasKey("DeviceId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("SetBoxFilesDevices");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Support", b =>
                {
                    b.Property<Guid>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SupportId");

                    b.Property<string>("Company")
                        .HasColumnName("Company")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreationDateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Telephone")
                        .HasColumnName("Telephone")
                        .HasMaxLength(50);

                    b.Property<string>("UrlApk")
                        .HasColumnName("UrlApk")
                        .HasMaxLength(4000);

                    b.Property<string>("UrlLogo")
                        .HasColumnName("UrlLogo")
                        .HasMaxLength(4000);

                    b.Property<string>("VersionApk")
                        .HasColumnName("VersionApk")
                        .HasMaxLength(20);

                    b.HasKey("SupportId");

                    b.ToTable("SetBoxSupport");
                });

            modelBuilder.Entity("SetBoxWebUI.Repository.ApplicationIdentityRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SetBoxWebUI.Repository.ApplicationIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SetBoxWebUI.Repository.ApplicationIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Address", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Company", "Company")
                        .WithMany("Address")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Config", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Device", "Device")
                        .WithOne("Configuration")
                        .HasForeignKey("SetBoxWebUI.Models.Config", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Contact", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.Device", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Company", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId");

                    b.HasOne("SetBoxWebUI.Models.Support", "Support")
                        .WithMany("Devices")
                        .HasForeignKey("SupportId");
                });

            modelBuilder.Entity("SetBoxWebUI.Models.DeviceLogAccesses", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Device", "Device")
                        .WithMany("LogAccesses")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.DeviceLogError", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Device", "Device")
                        .WithMany("Logs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SetBoxWebUI.Models.FilesDevices", b =>
                {
                    b.HasOne("SetBoxWebUI.Models.Device", "Device")
                        .WithMany("Files")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SetBoxWebUI.Models.FileCheckSum", "File")
                        .WithMany("Devices")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
